### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by namacilhdx11** [Riscue/ha-ai-memory#9]
Hi i installed on my HA-OS on a proxmox. i left most on default during installation but put my ollama installation on my pc for the agent end (i honestly dont even know how it works and why it needs it). 

im getting the following error:

Logger: homeassistant.components.llm
Source: components/llm/__init__.py:82
Integration: LLM ([documentation](https://www.home-assistant.io/integrations/llm), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+llm%22))
First occurred: 6:36:17 PM (8 occurrences)
Last logged: 6:46:09 PM
Error getting tools from LLM platform ai_memory

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/llm/__init__.py", line 82, in async_get_tools
    result = platform.async_get_tools(hass, llm_context, api_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'custom_components.ai_memory.llm' has no attribute 'async_get_tools'

this is maybe user error but at the off-chance of it not being that i guess you can get to me on DC:

namacilhdx (Astor)

i have a blond, bored looking guy as profilepic

**Comment by namacilhdx11** [comment]
also im sry for my comparatively lacking issue 😵‍💫

**Comment by namacilhdx11** [comment]
edit so "automatically" as proposed by the readme kinda lead me on a little bit... i just now saw the memory switch in the voice assistent panel so i think now its working. log entry still comes up though.

**Comment by Riscue** [comment]
Hi, thanks for reporting this. This error usually points to a mismatch between the Home Assistant core LLM API and the interface the integration expects, so I need a few version details to track it down:

1. What Home Assistant Core version are you running? (Settings > System > General)
2. Which "AI Conversation"/LLM integration are you using, and what version? (e.g. is it HA's built-in Ollama integration, or something else?)
3. What version of ha-ai-memory (ai_memory) do you have installed? (If installed via HACS, the install/update date would help too)

This will help me figure out exactly which combination is causing the issue.

**Comment by dCatfish** [comment]
Hi
I have the same problem.

AttributeError: module 'custom_components.ai_memory.llm' has no attribute 'async_get_tools'

1. HAOS, Core 2026.9.1
2. TF-IDF - HA generic Google Gemini integration (running Google AI Conversation, model gemini-3.1-flash-lite / cloud / Gemini API)
3. ha-ai-memory Version 0.2.1 installed via HACS today

**Comment by Riscue** [comment]
Thanks for the reports — this is fixed in the next release.
                                                                                                                                                      
Since HA 2026.6, the core llm integration auto-discovers any subpackage named llm/ in loaded integrations and calls a module-level async_get_tools hook on it. This integration happened to keep its internal LLM code in a subpackage named llm/ — a naming coincidence from before that hook existed — so HA 2026.6+ tried to use it as a platform and logged the AttributeError above.
                                                                                                                                                      
Impact was log noise only: memory tools are registered via async_register_api ("Memory Management" API), which kept working correctly on 2026.9.x as long as that API is selected for your agent. The package has been renamed to llm_api/ so HA no longer picks it up; verified on 2026.4.2 and 2026.9.1 that the error is gone and all tools remain intact. Update via HACS once the new version is out.

**Comment by Riscue** [comment]
Please update to v0.2.2 to see if the issue is resolved. If the problem persists, you can reopen this issue.
